####################################
## Tech Setting
####################################
BC_INDEX_FPATH: '/home1/jjackson10/FatFlies_scRNA/celseq2/barcodes.tab'
BC_IDs_DEFAULT: '1-96'
UMI_LENGTH: 6
BC_LENGTH: 6

####################################
## Alignment Tools
####################################
## Which RNA-seq aligner to use: 'bowtie2', 'star', 'kallisto'
ALIGNER: 'star'
## What is the absolute path to the command STAR?
STAR: 'STAR'
## Where is the directory to save STAR index?
STAR_INDEX_DIR: '/home1/jjackson10/FatFlies_scRNA/celseq2/dm6_ERCC_GAL4_GFP_STAR'

## Extra parameters to run aligner. For example:
## '--outSAMmultNmax 1 --outFilterScoreMinOverLread 0.3'
ALIGNER_EXTRA_PARAMETERS: ''

####################################
## Annotations ##
####################################
GFF: '/home1/jjackson10/FatFlies_scRNA/celseq2/dm6.refGene.CEL-Seq.gtf'
FEATURE_ID: 'gene_id'

####################################
## Demultiplexing
####################################
FASTQ_QUAL_MIN_OF_BC: 10
CUT_LENGTH: 35
SAVE_UNKNOWN_BC_FASTQ: false

####################################
## UMI Count
####################################
ALN_QUAL_MIN: 0

####################################
## Running Parameters
####################################
num_threads: 16
verbose: True
